# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='register',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brightness',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
