# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20170426_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brighnessLevel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='brightness',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
