# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20170509_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='brighnessLevel',
        ),
    ]
