# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_device_brighnesslevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightness',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
